# Biotools conda yaml
# :PROPERTIES:
# :ID:       cf13d347-1d0e-4858-a016-0a8a8af22609
# :header-args:yaml: :tangle ./config/biotools-conda-env.yaml
# :END:
# - [[file:biotools_env.yaml]]

name: biotools
channels:
  - conda-forge
  - bioconda

dependencies:
  - bamtools
  - bedops
  - bedtools
  - bowtie2
  - deeptools
  - fastp
  - fastqc
  - mosdepth
  - multiqc
  - pandas
  - picard
  - pybedtools
  - pysam
  - sambamba
  - samtools
  - snakemake
  - sra-tools
  - gffread
  - ucsc-gtftogenepred
  - ucsc-genepredtobed
  # R / Bioconductor
  - r-hmisc
  - r-survival
  - r-survminer
  - r-glmnet
  - r-readxl
  - r-dplyr
  - r-ggplot2
  - bioconductor-annotatr
  - bioconductor-genomicranges
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
